name: Create New Release
on: push
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        expr 3 + 7 > addition.txt
    - name: Upload sample site
      uses: actions/upload-artifact@v2
      with:
        name: sample-site
        path: addition.txt
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download site content
        uses: actions/download-artifact@v2
        with:
          name: sample-site
      - name: View content
        run: ls -R
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
